version: '3.4'

services:
  db:
    image: postgis/postgis:13-master
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: VINTAGEMAGIC
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: ISLANDCOLLAR
    volumes:
      - ./config/pgadmin4-servers.json:/pgadmin4/servers.json
