version: '3.4'

services:
  db:
    image: postgis/postgis:13-master
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: VINTAGEMAGIC
