// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EWS.Migrations
{
    [DbContext(typeof(EwsContext))]
    [Migration("20220728163010_UpdateDataExportView")]
    partial class UpdateDataExportView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
