// <auto-generated />
using System;
using EWS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EWS.Migrations
{
    [DbContext(typeof(EwsContext))]
    [Migration("20250918072517_NormalizeQualitaetBemerkungLinebreaks")]
    partial class NormalizeQualitaetBemerkungLinebreaks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
